# Generated by Django 6.0.2 on 2026-02-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_authors',
            field=models.TextField(blank=True, help_text="Comma-separated list of favorite authors, e.g. 'George R.R. Martin, Stephen King'", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_publishers',
            field=models.TextField(blank=True, help_text="Comma-separated list of favorite publishers, e.g. 'Planeta, Salamandra'", null=True),
        ),
    ]
