# Generated by Django 6.0.2 on 2026-02-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_editorial',
            field=models.BooleanField(default=False),
        ),
    ]
