# Generated by Django 6.0.2 on 2026-02-21 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Leyendo ahora'), ('read', 'Leído'), ('want_to_read', 'Quiero leer'), ('searching', 'Buscando conseguir')], default='want_to_read', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Private notes about this book', null=True)),
                ('rating', models.FloatField(blank=True, help_text='Rating 0-5 when finished', null=True)),
                ('review', models.TextField(blank=True, help_text='Final review when finished', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ol_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ol_author', models.CharField(blank=True, max_length=255, null=True)),
                ('ol_cover_url', models.URLField(blank=True, null=True)),
                ('ol_key', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_libraries', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserBookExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Leyendo ahora'), ('read', 'Leído'), ('want_to_read', 'Quiero leer'), ('searching', 'Buscando conseguir')], default='want_to_read', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('ol_key', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ol_key')},
            },
        ),
    ]
