# Generated by Django 6.0.2 on 2026-02-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_userbook_userbookexternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='chapter_notes',
            field=models.JSONField(blank=True, default=list, help_text='List of {chapter, note, created_at} dicts'),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='chapter_notes',
            field=models.JSONField(blank=True, default=list, help_text='List of {chapter, note, created_at} dicts'),
        ),
    ]
