# Generated by Django 6.0.2 on 2026-02-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_userbook_chapter_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='current_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbook',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='current_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
    ]
