# Generated by Django 6.0.2 on 2026-02-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userbook_current_chapter_userbook_total_chapters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookexternal',
            name='ol_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
