# Generated by Django 6.0.2 on 2026-02-22 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_userbookexternal_ol_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCoverContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ol_key', models.CharField(help_text='Open Library key e.g. /works/OL166894W', max_length=100)),
                ('cover_url', models.URLField(help_text='Cloudinary URL of the uploaded cover')),
                ('title', models.CharField(blank=True, help_text='Book title for display', max_length=255)),
                ('votes', models.IntegerField(default=0, help_text='Community upvotes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
                'unique_together': {('user', 'ol_key')},
            },
        ),
    ]
