# Generated by Django 6.0.2 on 2026-02-22 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookcovercontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('ol_key', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_type', models.CharField(choices=[('finish_by_date', 'Terminar para una fecha'), ('pages_per_day', 'Páginas por día'), ('chapters_per_day', 'Capítulos por día'), ('custom', 'Personalizado')], max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_chapters', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_goal_pages', models.IntegerField(default=0)),
                ('daily_goal_chapters', models.IntegerField(default=0)),
                ('current_page', models.IntegerField(default=0)),
                ('current_chapter', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pages_read', models.IntegerField(default=0)),
                ('chapters_read', models.IntegerField(default=0)),
                ('end_page', models.IntegerField(default=0)),
                ('end_chapter', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='books.readingchallenge')),
            ],
            options={
                'unique_together': {('challenge', 'date')},
            },
        ),
    ]
