# Generated by Django 6.0.2 on 2026-02-22 12:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_readingchallenge_dailyreadinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingchallenge',
            name='custom_cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
