# Generated by Django 6.0.2 on 2026-02-22 13:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_cachedrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='custom_cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='custom_cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
