# Generated by Django 6.0.2 on 2026-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_added_by_book_is_community_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookexternal',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
