# Generated by Django 6.0.2 on 2026-03-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_userbookexternal_current_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookexternal',
            name='ai_enriched',
            field=models.BooleanField(default=False, help_text='Whether AI enrichment has been applied'),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='ai_review',
            field=models.TextField(blank=True, help_text='AI-generated review', null=True),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='author_bio',
            field=models.TextField(blank=True, help_text='AI-generated author biography', null=True),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='synopsis',
            field=models.TextField(blank=True, help_text='AI-generated synopsis', null=True),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='themes',
            field=models.CharField(blank=True, help_text='Comma-separated themes', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='trivia',
            field=models.TextField(blank=True, help_text='AI-generated fun fact', null=True),
        ),
        migrations.AddField(
            model_name='userbookexternal',
            name='year_published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
