"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if 'RENDER' in os.environ:
        raise ValueError("DJANGO_SECRET_KEY environment variable is required in production!")
    # Only allow insecure default in local development
    SECRET_KEY = 'django-insecure-LOCAL-DEV-ONLY-CHANGE-ME'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
if DEBUG:
    ALLOWED_HOSTS = ['*']
elif 'RENDER' in os.environ:
    ALLOWED_HOSTS = [
        os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
        'appbook-backend.onrender.com',
        'localhost',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'cloudinary',
    'cloudinary_storage',
    # Local apps
    'users',
    'books',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'books', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://crleo1:@localhost:5432/book_tracker',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# CORS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Only in local development
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    ] or [
        'https://appbook-backend.onrender.com',
    ]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Google Auth
GOOGLE_WEB_CLIENT_ID = (
    os.environ.get('GOOGLE_WEB_CLIENT_ID', '')
    or os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
)
if not GOOGLE_WEB_CLIENT_ID and not DEBUG:
    print("WARNING: GOOGLE_WEB_CLIENT_ID not set in production!")

# ─── Cloudinary (Community Book Covers) ────────────────────────────────────
import cloudinary

_CLOUDINARY_CLOUD = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
_CLOUDINARY_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
_CLOUDINARY_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')

if not all([_CLOUDINARY_CLOUD, _CLOUDINARY_KEY, _CLOUDINARY_SECRET]) and not DEBUG:
    print("WARNING: Cloudinary credentials not fully configured!")

cloudinary.config(
    cloud_name = _CLOUDINARY_CLOUD,
    api_key    = _CLOUDINARY_KEY,
    api_secret = _CLOUDINARY_SECRET,
    secure     = True,
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _CLOUDINARY_CLOUD,
    'API_KEY':    _CLOUDINARY_KEY,
    'API_SECRET': _CLOUDINARY_SECRET,
}

# Django 5+ uses STORAGES dict instead of DEFAULT_FILE_STORAGE
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage" if not DEBUG else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ─── AI & External APIs ─────────────────────────────────────────────────
# OpenAI — for personalized book recommendations
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
if not OPENAI_API_KEY and not DEBUG:
    print("WARNING: OPENAI_API_KEY not set in production!")

# Google Books API — for richer search results
GOOGLE_BOOKS_API_KEY = os.environ.get('GOOGLE_BOOKS_API_KEY', '')
if not GOOGLE_BOOKS_API_KEY and not DEBUG:
    print("WARNING: GOOGLE_BOOKS_API_KEY not set in production!")

# Admin Panel Key — for author seeding and management endpoints
APPBOOK_ADMIN_KEY = os.environ.get('APPBOOK_ADMIN_KEY', 'appbook-admin-2026')
if APPBOOK_ADMIN_KEY == 'appbook-admin-2026' and not DEBUG:
    print("WARNING: APPBOOK_ADMIN_KEY using default value in production! Set a secure key.")

# ─── Email Configuration (Bug Reports) ──────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'cr.leonardo.ferreira@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # Gmail App Password
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AppBook <cr.leonardo.ferreira@gmail.com>')
BUG_REPORT_EMAIL = os.environ.get('BUG_REPORT_EMAIL', 'cr.leonardo.ferreira@gmail.com')
