# Generated by Django 6.0.2 on 2026-02-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_highlight_ol_key_highlight_ol_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('profile_type', models.CharField(choices=[('booktoker', 'Booktoker'), ('publisher', 'Editorial'), ('author', 'Autor')], max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('profile_url', models.URLField(help_text='Deep link or direct URL to the profile')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
